---
- name: apt-get | apt-get update
  apt: update_cache=yes cache_valid_time=3600
  tags: aptget
  sudo: true

- name: apt-get | ensure core packages are installed
  apt: pkg={{ item }} state=installed
  tags: aptget
  sudo: true
  with_items:
    - atool
    - atop
    - curl
    - git
    - make
    - mc
    - python-software-properties
    - tig
    - tree
    - vim
    - unzip
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - gawk
    - git-core
    - git
    - libxml2-dev
    - libffi-dev
    - libyaml-dev
    - libssl-dev
    - libsqlite3-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline6-dev
    - libtool
    - libyaml-dev
    - nfs-common # make virtualbox faster
    - pkg-config
    - sqlite3
    - vim
    - wget
    - zlib1g-dev
    - htop
    - iftop
    - python-pycurl # for postgresql playbook, uses apt_pkg
    - python-software-properties # for `add-apt-repository` command
    - fail2ban
    - ufw
    - unattended-upgrades
    - software-properties-common #add-apt-get-repository
    - mosh #ssh client
    - fail2ban #firewall
    - ntp
    - curl
    - ack-grep
    - acl
    - unattended-upgrades
    - policykit-1
    - unzip
    - htop
    - tmux
    - lsyncd  #rsync
