---
- name: PHP | Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags: laravel
  sudo: true

- name: PHP | Check if Laravel Installer is installed
  raw: ls /home/vagrant/.composer/vendor/bin/laravel
  register: laravel_installer
  ignore_errors: true
  tags: laravel

- name: PHP | Download Laravel Installer
  raw: composer global require "laravel/installer=~1.1"
  when: laravel_installer.stdout.find('No such file or directory') != -1
  tags: laravel
