---
- name: Test | NPM is installed
  shell: npm -v
  tags: test
  register: npm_installed
  ignore_errors: true

- name: NodeJS | Prepare for installation
  raw: "curl -sL https://deb.nodesource.com/setup | sudo bash -"
  tags: nodejs
  sudo: true
  when: npm_installed|failed

- name: NodeJS | Install NodeJS
  apt: name=nodejs state=present
  tags: nodejs
  sudo: true

- name: NodeJS | Install build-essentials package
  apt: name=build-essential state=present
  tags: nodejs
  sudo: true
