---
- name: Ruby | Uninstall Ruby and Rubygems
  apt: pkg={{ item }} state=absent purge=yes
  tags: ruby
  sudo: true
  with_items:
    - ruby

- name: Ruby | Install RVM
  shell: curl -L https://get.rvm.io | bash -s stable --quiet-curl --auto-dotfiles --ruby=2.1.3 creates=/home/{{ user }}/.rvm
  tags: ruby
  ignore_errors: true

- name: Ruby | Finalize rvm installation
  raw: source /home/{{ user }}/.rvm/scripts/rvm
  tags: ruby

- name: Ruby | Finalize rvm installation
  raw: source /home/{{ user }}/.bashrc
  tags: ruby

- name: Ruby | Update RubyGems via RVM
  shell: PATH=$PATH:/home/{{ user }}/.rvm/bin rvm rubygems latest
  tags: ruby

- name: Ruby | Get list of installed gems
  shell: /home/{{ user }}/.rvm/rubies/ruby-2.1.3/bin/gem list
  register: gem_list
  tags: ruby

- name: Ruby | Install sass and compass
  shell: /home/{{ user }}/.rvm/rubies/ruby-2.1.3/bin/gem install {{ item }}
  when: gem_list.stdout.find('{{ item }}') == -1
  tags: ruby
  with_items:
    - sass
    - compass
